[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r LittleLemon/requirements.txt"]

[start]
cmd = "python LittleLemon/manage.py runserver 0.0.0.0:8000"
