[build]
base = "python"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.django",
  "python311Packages.django-filter",
  "python311Packages.djangorestframework",
  "python311Packages.gunicorn",
  "python311Packages.psycopg2"
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.install]
cmds = [
  "python -m venv venv",
  "./venv/bin/pip install -r LittleLemon/requirements.txt"
]

[start]
cmd = "python LittleLemon/manage.py runserver 0.0.0.0:8000"

